# To get started with Dependabot version updates, you'll need to specify which
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/ChatGPT"
    allow:
      - dependency-name: "cloud.cleo.chimesma.squareup:lex-chatgpt-fullfill"
      - dependency-name: "cloud.cleo.chimesma.squareup:parent-pom"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      
