# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "squareup-chatgpt-ivr"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
region = "us-east-1"
parameter_overrides = "SMAID=\"d95bf7c0-6ae3-436f-9831-c5c362884b97\" VOICECONNECTORARN=\"arn:aws:chime:us-east-1:364253738352:vc/cze9epizslzqslzjpo58ff\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
profile = "CLEO"

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[east.deploy]
[east.deploy.parameters]
region = "us-east-1"
parameter_overrides = "SMAID=\"d95bf7c0-6ae3-436f-9831-c5c362884b97\" VOICECONNECTORARN=\"arn:aws:chime:us-east-1:364253738352:vc/cze9epizslzqslzjpo58ff\""
stack_name = "squareup-chatgpt-ivr"
resolve_s3 = true
s3_prefix = "squareup-chatgpt-ivr"
profile = "CLEO"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []


[west.deploy]
[west.deploy.parameters]
region = "us-west-2"
parameter_overrides = "SMAID=\"14f36d6f-4ecb-4629-ac87-bc11a04b5a35\" VOICECONNECTORARN=\"arn:aws:chime:us-west-2:364253738352:vc/dnpz57kzlmo6uvhb1anu3w\""
stack_name = "squareup-chatgpt-ivr"
resolve_s3 = true
s3_prefix = "squareup-chatgpt-ivr"
profile = "CLEO"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

