
name: CDK and SAM Deployment

on:
  push:
    branches: [ "main" ]


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency: deploy

env:
  # https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
  # Create secrets in the repository and they will be pushed to Parameter store, these are required
  SQUARE_API_KEY: ${{ secrets.SQUARE_API_KEY || 'DISABLED' }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  
    
  
  # https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
  # Create repository variables to override any/all of the below from the defaults
  #
  CDK_STACK_NAME: ${{ vars.CDK_STACK_NAME || 'chatgpt-square-ivr-cdk' }}
  STACK_NAME: ${{ vars.STACK_NAME || 'chatgpt-square-ivr' }}
  
  # The E164 Number to be used when transferring to main number
  TRANSFER_NUMBER: ${{ vars.TRANSFER_NUMBER || '+18004444444' }}
  
  # Set to PRODUCTION if you have a real Sqaure Buisness or Leave it as SANDBOX if you just have a dev account
  SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT || 'SANDBOX' }}
  # You can have many locations in Square, need to set to the location you want to query inventory or employees against (required for functions to work)
  SQUARE_LOCATION_ID: ${{ vars.SQUARE_LOCATION_ID || 'DISABLED' }}
  
  # https://platform.openai.com/docs/models/overview (requres model with function calling)
  OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-3.5-turbo-1106' }}
  
  # Define in repo variable if you want want to route main number calls via SIP via the Voice Connector
  PBX_HOSTNAME:  ${{ vars.PBX_HOSTNAME || '' }}
  
  # Polly voices to use for English and Spanish
  VOICE_ID_EN: ${{ vars.VOICE_ID_EN  || 'Joanna' }}
  VOICE_ID_ES: ${{ vars.VOICE_ID_ES  || 'Lupe' }}


jobs:
  # First we must create all the Chime resources like Voice Connectors, SIP Media Application, SIP Rules, etc.
  cdk-deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Set up Node we can install CDK
      uses: actions/setup-node@v4
      with:
        node-version: "18"
    
    - name: Install  CDK
      run: npm install -g aws-cdk
      
    - name: Setup AWS Creds using OIDC Role Method
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        # https://github.com/aws-actions/configure-aws-credentials#oidc
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        mask-aws-account-id: true
   
    - name: Ensure CDK is bootstraped
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        cdk bootstrap --ci=true aws://${ACCOUNT_ID}/us-east-1
        cdk bootstrap --ci=true aws://${ACCOUNT_ID}/us-west-2
        
    - name: Deploy Stack with CDK 
      working-directory: ./ChimeCDKProvision
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        # Deploy to both regions in parallel
        cdk deploy -c accountId=${ACCOUNT_ID} -c stackName=${CDK_STACK_NAME} -c regionEast=us-east-1 -c regionWest=us-west-2 --concurrency=2 --all --require-approval=never --ci=true
  
  # Now deploy the app into 2 regions at the same time via SAM with matrix job
  sam-deploy:
    strategy:
      matrix:
        region: [ us-east-1, us-west-2 ]
    runs-on: ubuntu-latest
    needs: [cdk-deploy]
    
    steps:     
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven     
       
    - name: Build up all the libraries
      # Exclude modules that SAM builds so it can use SAM cache and speed deploys
      run: mvn -B install -DskipTests --projects '!ChimeSMA,!ChatGPT,!ChimeCDKProvision,!cloud.cleo.chimesma:generate-poly-prompt'

    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Setup AWS Creds using OIDC Role Method
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ matrix.region }}
        # https://github.com/aws-actions/configure-aws-credentials#oidc
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
        mask-aws-account-id: true
      
      # You can manually go set this in SSM Parameter Store or use GitHub Secrets
    - name: Push Square API Key to Parameter store if set in Repository Secrets
      if: ${{ env.SQUARE_API_KEY != '' }}
      run: >
        aws ssm put-parameter
        --name /${STACK_NAME}/SQUARE_API_KEY
        --description "Square API Key used for stack ${STACK_NAME}"
        --type String
        --value ${{ secrets.SQUARE_API_KEY }}
        --overwrite
    
      # You can manually go set this in SSM Parameter Store or use GitHub Secrets
    - name: Push OpenAI API Key to Parameter store if set in Repository Secrets
      if: ${{ env.OPENAI_API_KEY != '' }}
      run: >
        aws ssm put-parameter
        --name /${STACK_NAME}/OPENAI_API_KEY
        --description "OpenAI API Key used for stack ${STACK_NAME}"
        --type String
        --value ${{ secrets.OPENAI_API_KEY }}
        --overwrite
    
    - name: Cache SAM Build files
      uses: actions/cache@v3
      with:
        path: .aws-sam
        key: ${{ runner.os }}-sam
       
    - name: SAM Build
      run: sam build
      
    - name: SAM Deploy
      run:  >
        sam deploy --no-fail-on-empty-changeset --no-confirm-changeset
        --region ${{ matrix.region }}
        --stack-name ${STACK_NAME}
        --parameter-overrides
        SQUAREAPIKEY=/${STACK_NAME}/SQUARE_API_KEY
        OPENAIAPIKEY=/${STACK_NAME}/OPENAI_API_KEY
        SMAID=/${CDK_STACK_NAME}/SMA_ID
        VOICECONNECTORARN=/${CDK_STACK_NAME}/VC_ARN
        SQUAREENVIRONMENT=${SQUARE_ENVIRONMENT}
        SQUARELOCATIONID=${SQUARE_LOCATION_ID}
        TRANSFERNUMBER=${TRANSFER_NUMBER}
        OPENAIMODEL=${OPENAI_MODEL}
        VOICEIDEN=${VOICE_ID_EN}
        VOICEIDES=${VOICE_ID_ES}
    
    - name: Update SMA Endpoint 
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        # The SMA ID is was pushed to param store by the CDK stack
        SMA_ID=$(aws ssm get-parameter --name /${CDK_STACK_NAME}/SMA_ID --query Parameter.Value --output text)
        # Chime for some reason loses reference to lambda, so always set to dummay and then back to what it should be
        TARGET_ENDPOINT=arn:aws:lambda:${{ matrix.region }}:${ACCOUNT_ID}:function:${STACK_NAME}-ChimeSMA
        DUMMY_ENDPOINT=$(aws ssm get-parameter --name /${CDK_STACK_NAME}/LAMBDA_ARN --query Parameter.Value --output text)
        aws chime-sdk-voice update-sip-media-application --sip-media-application-id ${SMA_ID} --endpoints LambdaArn=${DUMMY_ENDPOINT}
        aws chime-sdk-voice update-sip-media-application --sip-media-application-id ${SMA_ID} --endpoints LambdaArn=${TARGET_ENDPOINT}
       
        
            
      
