
name: CDK and SAM Deployment

on:
  push:
    branches: [ "main" ]


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  CDK_STACK_NAME: ${{ vars.CDK_STACK_NAME || 'chimesdk-cdk-provision' }}
  STACK_NAME: ${{ vars.STACK_NAME || 'squareup-chatgpt-ivr' }}
  TRANSFER_NUMBER: ${{ vars.TRANSFER_NUMBER || '+18004444444' }}
  SQUARE_ENVIRONMENT: ${{ vars.SQUARE_ENVIRONMENT || 'SANDBOX' }}
  OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-3.5-turbo-1106' }}
  # Define in repo variables if you want want to route main number calls via SIP
  PBX_HOSTNAME:  ${{ vars.PBX_HOSTNAME || '' }}

jobs:
  cdk-deploy:

    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Set up Node we can install CDK
      uses: actions/setup-node@v4
      with:
        node-version: "18"
    
    - name: Install  CDK
      run: npm install -g aws-cdk
    
    - name: Setup AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
    
    - name: Deploy Stack with CDK 
      working-directory: ./ChimeCDKProvision
      run: |
        ACCOUNT_ID=`aws sts get-caller-identity --query Account --output text`
        # Deploy to both regions in parallel
        cdk deploy -c accountId=${ACCOUNT_ID} -c stackName=${CDK_STACK_NAME} --concurrency=2 --all --require-approval=never --ci=true
  
  sam-deploy:
    strategy:
      matrix:
        region: [us-east-1,us-west-2]
    runs-on: ubuntu-latest
    needs: [cdk-deploy]
    
    steps:
        
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven     
       
    - name: Build up all the libraries
      # Exclude modules that SAM builds so it can use SAM cache and speed deploys
      run: mvn -B install -DskipTests --projects '!ChimeSMA,!ChatGPT,!ChimeCDKProvision,!cloud.cleo.chimesma:generate-poly-prompt'

    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - name: Setup AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ matrix.region }}
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
    
    - name: Cache SAM Build files
      uses: actions/cache@v3
      with:
        path: .aws-sam
        key: ${{ runner.os }}-sam
       
    - name: SAM Build
      run: sam build
      
    - name: SAM Deploy
      run:  >
        sam deploy --no-fail-on-empty-changeset --no-confirm-changeset --region ${{ matrix.region }}
        --stack-name $STACK_NAME
        --parameter-overrides
        SMAID=/${CDK_STACK_NAME}/SMA_ID
        VOICECONNECTORARN=/${CDK_STACK_NAME}/VC_ARN
        SQUAREENVIRONMENT=${SQUARE_ENVIRONMENT}
        TRANSFERNUMBER=${TRANSFER_NUMBER}
        OPENAIMODEL=${OPENAI_MODEL}
    
    - name: Update Endpoint
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        SMA_ID=$(aws ssm get-parameter --name /${CDK_STACK_NAME}/SMA_ID --query Parameter.Value --output text)
        CUR_ENDPOINT=$(aws chime get-sip-media-application --sip-media-application-id ${SMA_ID} --query 'SipMediaApplication.Endpoints[0].LambdaArn' --output text)
        TARGET_ENDPOINT=arn:aws:lambda:${{ matrix.region }}:${ACCOUNT_ID}:function:${STACK_NAME}-ChimeSMA
        if [[ $TARGET_ENDPOINT != $CUR_ENDPOINT ]]; then
            echo "SMA Lambda Endpoint needs to be updated"
            aws chime update-sip-media-application --sip-media-application-id ${SMA_ID} --endpoints LambdaArn=${TARGET_ENDPOINT}
        else
            echo "SMA Lambda Endpoint is already corectly set"
        fi
        
            
      
