## YAML Template.
name: Run Tests

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  STACK_NAME: ${{ vars.STACK_NAME || 'chatgpt-square-ivr' }}
  

jobs:
   # Run a couple tests to make sure ChatGPT is responding and able to make Square calls
  run-tests:
    if: ${{ vars.RUN_TESTS }}
    strategy:
      matrix:
        region: [ us-east-1, us-west-2 ]
    runs-on: ubuntu-latest
    environment: ${{ matrix.region }}
    steps:
      - name: Execute Tests
        uses: ./github/actions/test
        with:
          region: ${{ matrix.region }}
          stack-name: ${STACK_NAME}
    
      
